In [2]:
#https://blog.brunk.io/posts/similarity-search-with-duckdb

In [3]:
!pip install duckdb transformers FlagEmbedding polars pyarrow

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Collecting FlagEmbedding
  Downloading FlagEmbedding-1.3.5.tar.gz (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.9/163.9 kB 7.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: polars in /usr/local/lib/python3.12/dist-packages (1.25.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (2.8.0+cu126)
Requirement already satisfied: datasets>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (4.0.0)
Requirement already satisfied: accelerate>=0.20.1 in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (1.11.0)
Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (5.1.2)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (0.17.1)
Collecting ir-datasets (from FlagEmbedding)
  Downloading ir_datasets-0.5.11-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (0.2.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (5.29.5)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.1->FlagEmbedding) (5.9.5)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (3.4.0)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from ir-datasets->FlagEmbedding) (4.13.5)
Collecting inscriptis>=2.2.0 (from ir-datasets->FlagEmbedding)
  Downloading inscriptis-2.6.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.12/dist-packages (from ir-datasets->FlagEmbedding) (5.4.0)
Collecting trec-car-tools>=2.5.4 (from ir-datasets->FlagEmbedding)
  Downloading trec_car_tools-2.6-py3-none-any.whl.metadata (640 bytes)
Collecting lz4>=3.1.10 (from ir-datasets->FlagEmbedding)
  Downloading lz4-4.4.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting warc3-wet>=0.2.3 (from ir-datasets->FlagEmbedding)
  Downloading warc3_wet-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting warc3-wet-clueweb09>=0.2.5 (from ir-datasets->FlagEmbedding)
  Downloading warc3-wet-clueweb09-0.2.5.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting zlib-state>=0.1.3 (from ir-datasets->FlagEmbedding)
  Downloading zlib_state-0.1.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Collecting ijson>=3.1.3 (from ir-datasets->FlagEmbedding)
  Downloading ijson-3.4.0.post0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting unlzw3>=0.2.1 (from ir-datasets->FlagEmbedding)
  Downloading unlzw3-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence_transformers->FlagEmbedding) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence_transformers->FlagEmbedding) (1.16.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence_transformers->FlagEmbedding) (11.3.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->ir-datasets->FlagEmbedding) (2.8)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (3.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6.0->FlagEmbedding) (1.3.0)
Collecting cbor>=1.0.0 (from trec-car-tools>=2.5.4->ir-datasets->FlagEmbedding)
  Downloading cbor-1.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.6.0->FlagEmbedding) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.19.0->FlagEmbedding) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.19.0->FlagEmbedding) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.19.0->FlagEmbedding) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers->FlagEmbedding) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers->FlagEmbedding) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.19.0->FlagEmbedding) (1.17.0)
Downloading ir_datasets-0.5.11-py3-none-any.whl (866 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 35.4 MB/s eta 0:00:00
Downloading ijson-3.4.0.post0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (149 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.0/149.0 kB 17.1 MB/s eta 0:00:00
Downloading inscriptis-2.6.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.1/45.1 kB 4.6 MB/s eta 0:00:00
Downloading lz4-4.4.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 68.1 MB/s eta 0:00:00
Downloading trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Downloading unlzw3-0.2.3-py3-none-any.whl (6.7 kB)
Downloading warc3_wet-0.2.5-py3-none-any.whl (18 kB)
Downloading zlib_state-0.1.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Building wheels for collected packages: FlagEmbedding, warc3-wet-clueweb09, cbor
  Building wheel for FlagEmbedding (setup.py) ... done
  Created wheel for FlagEmbedding: filename=FlagEmbedding-1.3.5-py3-none-any.whl size=233746 sha256=5cc00510521517d8fa48417d087696e65694095a0c6b407f9dce7d093912274b
  Stored in directory: /root/.cache/pip/wheels/b2/1f/f6/78f862bb80cb959cc9960b7c4e2d1f702b1bc0e79d19b5f124
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Created wheel for warc3-wet-clueweb09: filename=warc3_wet_clueweb09-0.2.5-py3-none-any.whl size=18919 sha256=90dd7a121669df445e9a49f4b0068c93deb20968ef451b05fcf4bf9278b2ff70
  Stored in directory: /root/.cache/pip/wheels/f6/85/c2/9f0f621def52a1d5db7d29984f81e45f9fb6dfeb1a4eb6e31c
  Building wheel for cbor (setup.py) ... done
  Created wheel for cbor: filename=cbor-1.0.0-cp312-cp312-linux_x86_64.whl size=55023 sha256=1e14de7bf6af9948b3f396904117d5d16d45a7054c6dfa79a2892c6954e96245
  Stored in directory: /root/.cache/pip/wheels/44/3e/21/a739cbcc331a1ab45c326d6edbdac6118de4402f6076e30ff1
Successfully built FlagEmbedding warc3-wet-clueweb09 cbor
Installing collected packages: warc3-wet-clueweb09, warc3-wet, cbor, zlib-state, unlzw3, trec-car-tools, lz4, ijson, inscriptis, ir-datasets, FlagEmbedding
Successfully installed FlagEmbedding-1.3.5 cbor-1.0.0 ijson-3.4.0.post0 inscriptis-2.6.0 ir-datasets-0.5.11 lz4-4.4.4 trec-car-tools-2.6 unlzw3-0.2.3 warc3-wet-0.2.5 warc3-wet-clueweb09-0.2.5 zlib-state-0.1.10

In [4]:
import duckdb
from FlagEmbedding import BGEM3FlagModel
import torch


con = duckdb.connect()
con.install_extension("vss")
con.load_extension("vss")

sql="""SET GLOBAL hnsw_enable_experimental_persistence = true;"""

con.execute(sql)

In [5]:
qry = """FROM 'hf://datasets/wikimedia/wikipedia/20231101.en/*.parquet'
SELECT count(*) AS count;"""

con.execute(qry).fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     count
0  6407814

In [6]:
qry = """FROM 'hf://datasets/wikimedia/wikipedia/20231101.en/*.parquet'
SELECT * LIMIT 10;"""

con.execute(qry).fetchdf()

,id,url,title,text
0,12,https://en.wikipedia.org/wiki/Anarchism,Anarchism,Anarchism is a political philosophy and moveme...
1,39,https://en.wikipedia.org/wiki/Albedo,Albedo,Albedo (; ) is the fraction of sunlight that i...
2,290,https://en.wikipedia.org/wiki/A,A,"A, or a, is the first letter and the first vow..."
3,303,https://en.wikipedia.org/wiki/Alabama,Alabama,Alabama () is a state in the Southeastern regi...
4,305,https://en.wikipedia.org/wiki/Achilles,Achilles,"In Greek mythology, Achilles ( ) or Achilleus ..."
5,307,https://en.wikipedia.org/wiki/Abraham%20Lincoln,Abraham Lincoln,"Abraham Lincoln ( ; February 12, 1809 – April ..."
6,308,https://en.wikipedia.org/wiki/Aristotle,Aristotle,"Aristotle (; Aristotélēs, ; 384–322 BC) was a..."
7,309,https://en.wikipedia.org/wiki/An%20American%20...,An American in Paris,An American in Paris is a jazz-influenced symp...
8,316,https://en.wikipedia.org/wiki/Academy%20Award%...,Academy Award for Best Production Design,The Academy Award for Best Production Design r...
9,324,https://en.wikipedia.org/wiki/Academy%20Awards,Academy Awards,"The Academy Awards, mainly known as the Oscars..."

In [7]:
device = "cpu"
# use a GPU if available to speed up the embedding computation
if torch.cuda.is_available(): device = "cuda" # Nvidia GPU
elif torch.backends.mps.is_available(): device = "mps" # Apple silicon GPU

model = BGEM3FlagModel('BAAI/bge-m3', use_fp16=True, device=device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

.gitattributes: 0.00B [00:00, ?B/s]

.DS_Store:   0%|          | 0.00/6.15k [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

bm25.jpg:   0%|          | 0.00/132k [00:00<?, ?B/s]

colbert_linear.pt:   0%|          | 0.00/2.10M [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

long.jpg:   0%|          | 0.00/485k [00:00<?, ?B/s]

others.webp:   0%|          | 0.00/21.0k [00:00<?, ?B/s]

nqa.jpg:   0%|          | 0.00/158k [00:00<?, ?B/s]

miracl.jpg:   0%|          | 0.00/576k [00:00<?, ?B/s]

mkqa.jpg:   0%|          | 0.00/608k [00:00<?, ?B/s]

long.jpg:   0%|          | 0.00/127k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/698 [00:00<?, ?B/s]

Constant_7_attr__value:   0%|          | 0.00/65.6k [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

onnx/model.onnx:   0%|          | 0.00/725k [00:00<?, ?B/s]

onnx/model.onnx_data:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

onnx/tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

sparse_linear.pt:   0%|          | 0.00/3.52k [00:00<?, ?B/s]

In [8]:
print(device)

cuda

In [9]:
#Aside
queries = ["What is BGE M3?", "What is DuckDB?"]
documents = [
    "BGE M3 is an embedding model supporting dense retrieval, lexical matching and multi-vector interaction.",
    "DuckDB is a fast in-process analytical database. It supports a feature-rich SQL dialect complemented with deep integrations into client APIs",
]

query_embeddings = model.encode(queries)["dense_vecs"]
document_embeddings = model.encode(documents)["dense_vecs"]

similarity = query_embeddings @ document_embeddings.T
similarity

You're using a XLMRobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

array([[0.626 , 0.1917],
       [0.3362, 0.7314]], dtype=float16)

In [10]:
qry = """CREATE TABLE wikipedia AS
FROM 'hf://datasets/wikimedia/wikipedia/20231101.en/*.parquet'
SELECT * limit 200;"""

con.execute(qry)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [11]:
con.execute("SELECT * FROM wikipedia LIMIT 10").fetch_df()

,id,url,title,text
0,12,https://en.wikipedia.org/wiki/Anarchism,Anarchism,Anarchism is a political philosophy and moveme...
1,39,https://en.wikipedia.org/wiki/Albedo,Albedo,Albedo (; ) is the fraction of sunlight that i...
2,290,https://en.wikipedia.org/wiki/A,A,"A, or a, is the first letter and the first vow..."
3,303,https://en.wikipedia.org/wiki/Alabama,Alabama,Alabama () is a state in the Southeastern regi...
4,305,https://en.wikipedia.org/wiki/Achilles,Achilles,"In Greek mythology, Achilles ( ) or Achilleus ..."
5,307,https://en.wikipedia.org/wiki/Abraham%20Lincoln,Abraham Lincoln,"Abraham Lincoln ( ; February 12, 1809 – April ..."
6,308,https://en.wikipedia.org/wiki/Aristotle,Aristotle,"Aristotle (; Aristotélēs, ; 384–322 BC) was a..."
7,309,https://en.wikipedia.org/wiki/An%20American%20...,An American in Paris,An American in Paris is a jazz-influenced symp...
8,316,https://en.wikipedia.org/wiki/Academy%20Award%...,Academy Award for Best Production Design,The Academy Award for Best Production Design r...
9,324,https://en.wikipedia.org/wiki/Academy%20Awards,Academy Awards,"The Academy Awards, mainly known as the Oscars..."

In [12]:
qry = """CREATE TABLE embeddings(
     doc_id VARCHAR,
     embedding FLOAT[1024]
);"""

con.execute(qry)

In [13]:
import pyarrow as pa
import numpy as np

reader = con.execute(
    "FROM wikipedia SELECT id, text WHERE id NOT IN (FROM embeddings select doc_id);"
).fetch_record_batch(100)

for batch in reader: # 100 records per batch
    # 4 records per GPU batch
    embeddings = model.encode(batch["text"].tolist(), batch_size=4)["dense_vecs"].astype(np.float32)
    # add our embeddings to the batch
    # We will now directly insert into the table instead of using a temporary Arrow table
    for i in range(len(batch)):
        con.cursor().execute(
            "INSERT INTO embeddings (doc_id, embedding) VALUES (?, ?);",
            [batch["id"][i].as_py(), embeddings[i].tolist()]
        )

pre tokenize: 100%|██████████| 25/25 [00:02<00:00, 11.47it/s]
Inference Embeddings: 100%|██████████| 25/25 [00:01<00:00, 13.69it/s]
pre tokenize: 100%|██████████| 25/25 [00:01<00:00, 13.12it/s]
Inference Embeddings: 100%|██████████| 25/25 [00:01<00:00, 13.59it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [14]:
sql = """FROM wikipedia JOIN embeddings ON (wikipedia.id = embeddings.doc_id)
SELECT *
LIMIT 5;"""

con.execute(sql).fetch_df()

,id,url,title,text,doc_id,embedding
0,12,https://en.wikipedia.org/wiki/Anarchism,Anarchism,Anarchism is a political philosophy and moveme...,12,"[0.02633667, -0.0013446808, 0.0079574585, 0.00..."
1,39,https://en.wikipedia.org/wiki/Albedo,Albedo,Albedo (; ) is the fraction of sunlight that i...,39,"[-0.028518677, 0.009605408, -0.04446411, -0.02..."
2,290,https://en.wikipedia.org/wiki/A,A,"A, or a, is the first letter and the first vow...",290,"[-0.00059890747, 0.012763977, -0.015975952, -0..."
3,303,https://en.wikipedia.org/wiki/Alabama,Alabama,Alabama () is a state in the Southeastern regi...,303,"[-0.0011062622, -0.0032577515, -0.027740479, -..."
4,305,https://en.wikipedia.org/wiki/Achilles,Achilles,"In Greek mythology, Achilles ( ) or Achilleus ...",305,"[-0.00390625, 0.0021438599, -0.035064697, 0.01..."

In [15]:

from duckdb.typing import VARCHAR

def embed(sentence: str) -> np.ndarray:
    return model.encode(sentence)['dense_vecs']

con.create_function("embed", embed, [VARCHAR], 'FLOAT[1024]')


qry = "SELECT embed('Who was the first human on the moon?') AS query_embedding;"
con.execute(qry).fetch_df()

                                     query_embedding
0  [0.011383057, 0.010261536, -0.058807373, -0.04...

In [16]:
def search(q: str):
    return con.execute("""
        FROM embeddings JOIN wikipedia ON (wikipedia.id = embeddings.doc_id)
        SELECT wikipedia.id, title, array_inner_product(embedding, embed($q)) AS similarity
        ORDER BY similarity DESC
        LIMIT 5""",
        {"q": q}
    ).pl()

search('Who was the first human on the moon?')

shape: (5, 3)
┌─────┬─────────────────────────┬────────────┐
│ id  ┆ title                   ┆ similarity │
│ --- ┆ ---                     ┆ ---        │
│ str ┆ str                     ┆ f32        │
╞═════╪═════════════════════════╪════════════╡
│ 662 ┆ Apollo 11               ┆ 0.677635   │
│ 663 ┆ Apollo 8                ┆ 0.612966   │
│ 664 ┆ Astronaut               ┆ 0.45167    │
│ 728 ┆ List of anthropologists ┆ 0.43085    │
│ 784 ┆ Alfred Korzybski        ┆ 0.420688   │
└─────┴─────────────────────────┴────────────┘

In [17]:
qry = """CREATE INDEX vec_idx ON embeddings USING HNSW (embedding)
WITH (metric = 'cosine');"""
con.execute(qry)

In [19]:
q = "Who was the first person on the moon?"

qry="""WITH top_k AS (
    FROM embeddings SELECT *
    ORDER BY array_inner_product(embedding, embed($q)) DESC
    LIMIT 5)
FROM top_k JOIN wikipedia ON (wikipedia.id = top_k.doc_id)
SELECT wikipedia.id, title, array_inner_product(embedding, embed($q)) AS similarity
ORDER BY similarity DESC"""

con.execute(qry, {"q": q}).fetch_df()

    id                    title  similarity
0  662                Apollo 11    0.673158
1  663                 Apollo 8    0.610035
2  664                Astronaut    0.470620
3  728  List of anthropologists    0.447238
4  851             Alfred Nobel    0.422824